package com.projectomega.main.versions.v16;

import com.projectomega.main.game.Material;
import com.projectomega.main.game.block.BlockDataTag;
import com.projectomega.main.game.entity.EntityType;
import com.projectomega.main.packets.PacketType;
import com.projectomega.main.versions.ProtocolHandler;

public class ProtocolHandler16 extends ProtocolHandler {


    public ProtocolHandler16() {
        packetIDs.put(PacketType.SPAWN_ENTITY, 0x00);
        packetIDs.put(PacketType.SPAWN_LIVING_ENTITY, 0x02);
        packetIDs.put(PacketType.CLIENT_STATUS, 0x04);
        packetIDs.put(PacketType.BLOCK_CHANGE, 0x08);
        packetIDs.put(PacketType.BOSS_BAR, 0x0C);
        packetIDs.put(PacketType.CHAT_CLIENTBOUND, 0x0E);
        packetIDs.put(PacketType.PLAYER_POSITION, 0x12);
        packetIDs.put(PacketType.WINDOW_ITEMS, 0x13);
        packetIDs.put(PacketType.SET_SLOT, 0x15);
        packetIDs.put(PacketType.DISCONNECT,0x1B);
        packetIDs.put(PacketType.KEEP_ALIVE_CLIENTBOUND, 0x1F);
        packetIDs.put(PacketType.CHUNK_DATA, 0x20);
        packetIDs.put(PacketType.JOIN_GAME, 0x24);
        packetIDs.put(PacketType.OPEN_WINDOW, 0x2D);
        packetIDs.put(PacketType.PLAYER_INFO, 0x32);
        packetIDs.put(PacketType.PLAYER_POSITION_AND_LOOK, 0x34);
        packetIDs.put(PacketType.RESPAWN, 0x39);
        packetIDs.put(PacketType.MULTI_BLOCK_CHANGE, 0x3B);
        packetIDs.put(PacketType.HELD_ITEM_CHANGE, 0x3F);
        packetIDs.put(PacketType.UPDATE_VIEW_POSITION, 0x40);
        packetIDs.put(PacketType.UPDATE_VIEW_DISTANCE, 0x41);
        packetIDs.put(PacketType.ENTITY_METADATA, 0x44);
        packetIDs.put(PacketType.SET_EXPERIENCE, 0x48);
        packetIDs.put(PacketType.UPDATE_HEALTH, 0x49);
        packetIDs.put(PacketType.TIME_UPDATE, 0x4E);
        packetIDs.put(PacketType.TITLE, 0x4F);
        packetIDs.put(PacketType.SOUND_EFFECT, 0x51);
        packetIDs.put(PacketType.ENTITY_TELEPORT, 0x56);

        packetIDs.put(PacketType.STATUS_PING, 0);
        packetIDs.put(PacketType.LOGIN_SUCCESS, 2);
        packetIDs.put(PacketType.CHAT_SERVERBOUND, 0x03);
        packetIDs.put(PacketType.CLIENT_SETTINGS, 0x05);
        packetIDs.put(PacketType.CLICK_WINDOW_BUTTON, 0x08);
        packetIDs.put(PacketType.CLICK_WINDOW, 0x09);
        packetIDs.put(PacketType.KEEP_ALIVE_SERVERBOUND, 0x10);
        packetIDs.put(PacketType.PLAYER_POSITION_AND_ROTATION, 0x13);
        packetIDs.put(PacketType.HELD_ITEM_CHANGE_SERVERBOUND, 0x25);


        entityIDs.put(EntityType.AREA_EFFECT_CLOUD, 0);
        entityIDs.put(EntityType.ARMOR_STAND, 1);
        entityIDs.put(EntityType.ARROW, 2);
        entityIDs.put(EntityType.BAT, 3);
        entityIDs.put(EntityType.BEE, 4);
        entityIDs.put(EntityType.BLAZE, 5);
        entityIDs.put(EntityType.BOAT, 6);
        entityIDs.put(EntityType.CAT, 7);
        entityIDs.put(EntityType.CAVESPIDER, 8);
        entityIDs.put(EntityType.CHICKEN, 9);
        entityIDs.put(EntityType.COD, 10);
        entityIDs.put(EntityType.COW, 11);
        entityIDs.put(EntityType.CREEPER, 12);
        entityIDs.put(EntityType.DONKEY, 13);
        entityIDs.put(EntityType.DOLPHIN, 14);
        entityIDs.put(EntityType.DRAGON_FIREBALL, 15);
        entityIDs.put(EntityType.DROWNED, 16);
        entityIDs.put(EntityType.ELDER_GUADIAN, 17);
        entityIDs.put(EntityType.ENDER_CRYSTAL, 18);
        entityIDs.put(EntityType.ENDER_DRAGON, 19);
        entityIDs.put(EntityType.ENDERMAN, 20);
        entityIDs.put(EntityType.ENDERMITE, 21);
        entityIDs.put(EntityType.EVOCATION_FANG, 22);
        entityIDs.put(EntityType.EVOCATIONILLAGER, 23);
        entityIDs.put(EntityType.EYE_IF_ENDER_SIGNAL, 25);
        entityIDs.put(EntityType.FALLING_SAND, 26);
        entityIDs.put(EntityType.FIREWORK_ROCKET, 27);
        entityIDs.put(EntityType.FOX, 28);
        entityIDs.put(EntityType.GHAST, 29);
        entityIDs.put(EntityType.GIANT, 30);
        entityIDs.put(EntityType.GUARDIAN, 31);
        entityIDs.put(EntityType.HOGLIN, 32);
        entityIDs.put(EntityType.HORSE, 33);
        entityIDs.put(EntityType.HUSK, 34);
        entityIDs.put(EntityType.ILLUSION_ILLAGER, 35);
        entityIDs.put(EntityType.IRON_GOLEM, 36);
        entityIDs.put(EntityType.ITEM, 37);
        entityIDs.put(EntityType.ITEM_FRAME, 38);
        entityIDs.put(EntityType.FIREBALL, 39);
        entityIDs.put(EntityType.LEASH_KNOT, 40);
        entityIDs.put(EntityType.LIGHTNING_BOLT, 41);
        entityIDs.put(EntityType.LLAMA, 42);
        entityIDs.put(EntityType.LLAMA_SPIT, 43);
        entityIDs.put(EntityType.MAGMA_CUBE, 44);
        entityIDs.put(EntityType.MINECART, 45);
        entityIDs.put(EntityType.MINECART_CHEST, 46);
        entityIDs.put(EntityType.MINECART_COMMANDBLOCK, 47);
        entityIDs.put(EntityType.MINECART_FURNACE, 48);
        entityIDs.put(EntityType.MINECART_HOPPER, 49);
        entityIDs.put(EntityType.MINECART_SPAWNER, 50);
        entityIDs.put(EntityType.MINECART_TNT, 51);
        entityIDs.put(EntityType.MULE, 52);
        entityIDs.put(EntityType.MUSHROOM_COW, 53);
        entityIDs.put(EntityType.OZELOT, 54);
        entityIDs.put(EntityType.PAINTING, 55);
        entityIDs.put(EntityType.PANDA, 56);
        entityIDs.put(EntityType.PARROT, 57);
        entityIDs.put(EntityType.PHANTOM, 58);
        entityIDs.put(EntityType.PIG, 59);
        entityIDs.put(EntityType.PIGLIN, 60);
        entityIDs.put(EntityType.PIGLIN_BRUTE, 51);
        entityIDs.put(EntityType.PILLAGER, 62);
        entityIDs.put(EntityType.POLAR_BEAR, 63);
        entityIDs.put(EntityType.PRIMED_TNT, 64);
        entityIDs.put(EntityType.PUFFERFISH, 65);
        entityIDs.put(EntityType.RABBIT, 66);
        entityIDs.put(EntityType.RAVAGER, 67);
        entityIDs.put(EntityType.SALMON, 68);
        entityIDs.put(EntityType.SHEEP, 69);
        entityIDs.put(EntityType.SHULKER, 70);
        entityIDs.put(EntityType.SHULKER_BULLET, 71);
        entityIDs.put(EntityType.SILVERFISH, 72);
        entityIDs.put(EntityType.SKELETON, 73);
        entityIDs.put(EntityType.SKELETON_HORSE, 74);
        entityIDs.put(EntityType.SLIME, 75);
        entityIDs.put(EntityType.SMALL_FIREBALL, 76);
        entityIDs.put(EntityType.SNOWMAN, 77);
        entityIDs.put(EntityType.SNOWBALL, 78);
        entityIDs.put(EntityType.SPECTRAL_ARROW, 79);
        entityIDs.put(EntityType.SPIDER, 80);
        entityIDs.put(EntityType.SQUID, 81);
        entityIDs.put(EntityType.STRAY, 82);
        entityIDs.put(EntityType.STRIDER, 83);
        entityIDs.put(EntityType.THROWN_EGG, 84);
        entityIDs.put(EntityType.THROWN_ENDERPEARL, 85);
        entityIDs.put(EntityType.THROWN_EXP_BOTTLE, 86);
        entityIDs.put(EntityType.THROWN_POTION, 87);
        entityIDs.put(EntityType.THROWN_TRIDENT, 88);
        entityIDs.put(EntityType.TRADER_LLAMA, 89);
        entityIDs.put(EntityType.TROPICAL_FISH, 90);
        entityIDs.put(EntityType.TURTLE, 91);
        entityIDs.put(EntityType.VEX, 92);
        entityIDs.put(EntityType.VILLAGER, 93);
        entityIDs.put(EntityType.VINDICATER, 94);
        entityIDs.put(EntityType.WANDERING_TRADER, 95);
        entityIDs.put(EntityType.WITCH, 96);
        entityIDs.put(EntityType.WITHER_BOSS, 97);
        entityIDs.put(EntityType.WITHER_SKELETON, 98);
        entityIDs.put(EntityType.WITHER_SKULL, 99);
        entityIDs.put(EntityType.WOLF, 100);
        entityIDs.put(EntityType.ZOGLIN, 101);
        entityIDs.put(EntityType.ZOMBIE, 102);
        entityIDs.put(EntityType.ZOMBIE_HORSE, 103);
        entityIDs.put(EntityType.ZOMBIE_VILLAGER, 104);
        entityIDs.put(EntityType.ZOMBIE_PIGMAN, 105);
        entityIDs.put(EntityType.PLAYER, 106);
        entityIDs.put(EntityType.FISHING_BOBBER, 107);

        registerBlockData(Material.AIR);
        registerBlockData(Material.STONE);
        registerBlockData(Material.GRANITE);
        registerBlockData(Material.POLISHED_GRANITE);
        registerBlockData(Material.DIORITE);
        registerBlockData(Material.POLISHED_DIORITE);
        registerBlockData(Material.ANDESITE);
        registerBlockData(Material.POLISHED_ANDESITE);
        registerBlockData(Material.GRASS_BLOCK, BlockDataTag.GRASS);
        registerBlockData(Material.DIRT);
        registerBlockData(Material.COARSE_DIRT);
        registerBlockData(Material.PODZOL, BlockDataTag.GRASS);
        registerBlockData(Material.COBBLESTONE);
        registerBlockData(Material.OAK_PLANKS);
        registerBlockData(Material.SPRUCE_PLANKS);
        registerBlockData(Material.BIRCH_PLANKS);
        registerBlockData(Material.JUNGLE_PLANKS);
        registerBlockData(Material.ACACIA_PLANKS);
        registerBlockData(Material.DARK_OAK_PLANKS);
        registerBlockData(Material.OAK_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.SPRUCE_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.BIRCH_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.JUNGLE_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.ACACIA_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.DARK_OAK_SAPLING, BlockDataTag.SAPLING);
        registerBlockData(Material.BEDROCK);
        registerBlockData(Material.WATER, BlockDataTag.WATER_LEVEL, BlockDataTag.WATER_FALLING);
        registerBlockData(Material.LAVA, BlockDataTag.WATER_LEVEL, BlockDataTag.WATER_FALLING);
        registerBlockData(Material.SAND);
        registerBlockData(Material.RED_SAND);
        registerBlockData(Material.GRAVEL);
        registerBlockData(Material.GOLD_ORE);
        registerBlockData(Material.IRON_ORE);
        registerBlockData(Material.COAL_ORE);
        registerBlockData(Material.NETHER_GOLD_ORE);
        registerBlockData(Material.OAK_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.SPRUCE_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.BIRCH_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.JUNGLE_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.ACACIA_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.DARK_OAK_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_SPRUCE_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_BIRCH_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_JUNGLE_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_ACACIA_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_DARK_OAK_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_OAK_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.OAK_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.SPRUCE_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.BIRCH_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.JUNGLE_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.ACACIA_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.DARK_OAK_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_OAK_LOG, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_SPRUCE_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_BIRCH_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_JUNGLE_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_ACACIA_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_DARK_OAK_WOOD, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.OAK_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.SPRUCE_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.BIRCH_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.JUNGLE_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.ACACIA_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.DARK_OAK_LEAVES, BlockDataTag.PERSISTANT, BlockDataTag.LEAVES_LEVEL);
        registerBlockData(Material.SPONGE);
        registerBlockData(Material.WET_SPONGE);
        registerBlockData(Material.GLASS);
        registerBlockData(Material.LAPIS_ORE);
        registerBlockData(Material.LAPIS_BLOCK);
        registerBlockData(Material.DISPENSER, BlockDataTag.DIRECTION, BlockDataTag.TRIGGERED);
        registerBlockData(Material.NOTE_BLOCK, BlockDataTag.POWERED, BlockDataTag.NOTEBLOCK_TONE, BlockDataTag.NOTEBLOCK_TYPE);
        registerBlockData(Material.WHITE_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.ORANGE_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.MAGENTA_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.LIGHT_BLUE_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.YELLOW_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.LIME_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.PINK_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.GRAY_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.LIGHT_GRAY_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.CYAN_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.PURPLE_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.BLUE_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.BROWN_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.GREEN_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.RED_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.BLACK_BED, BlockDataTag.BED_HEADFOOT, BlockDataTag.BED_OCCUPIED, BlockDataTag.FACING);
        registerBlockData(Material.POWERED_RAIL, BlockDataTag.POWERED_RAIL_FACING, BlockDataTag.POWERED);
        registerBlockData(Material.DETECTOR_RAIL, BlockDataTag.POWERED_RAIL_FACING, BlockDataTag.POWERED);
        registerBlockData(Material.STICKY_PISTON, BlockDataTag.DIRECTION, BlockDataTag.PISTON_EXTENDED);
        registerBlockData(Material.COBWEB);
        registerBlockData(Material.GRASS);
        registerBlockData(Material.FERN);
        registerBlockData(Material.DEAD_BUSH);
        registerBlockData(Material.SEAGRASS);
        registerBlockData(Material.TALL_GRASS, BlockDataTag.TWO_TALL);
        registerBlockData(Material.PISTON, BlockDataTag.DIRECTION, BlockDataTag.PISTON_EXTENDED);
        registerBlockData(Material.PISTON_HEAD, BlockDataTag.PISTON_HEAD_STICKY, BlockDataTag.DIRECTION);
        registerBlockData(Material.WHITE_WOOL);
        registerBlockData(Material.ORANGE_WOOL);
        registerBlockData(Material.MAGENTA_WOOL);
        registerBlockData(Material.LIGHT_BLUE_WOOL);
        registerBlockData(Material.YELLOW_WOOL);
        registerBlockData(Material.LIME_WOOL);
        registerBlockData(Material.PINK_WOOL);
        registerBlockData(Material.GRAY_WOOL);
        registerBlockData(Material.LIGHT_GRAY_WOOL);
        registerBlockData(Material.CYAN_WOOL);
        registerBlockData(Material.PURPLE_WOOL);
        registerBlockData(Material.BLUE_WOOL);
        registerBlockData(Material.BROWN_WOOL);
        registerBlockData(Material.GREEN_WOOL);
        registerBlockData(Material.RED_WOOL);
        registerBlockData(Material.BLACK_WOOL);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.AIR);
        registerBlockData(Material.DANDELION);
        registerBlockData(Material.POPPY);
        registerBlockData(Material.BLUE_ORCHID);
        registerBlockData(Material.ALLIUM);
        registerBlockData(Material.AZURE_BLUET);
        registerBlockData(Material.RED_TULIP);
        registerBlockData(Material.ORANGE_TULIP);
        registerBlockData(Material.WHITE_TULIP);
        registerBlockData(Material.PINK_TULIP);
        registerBlockData(Material.OXEYE_DAISY);
        registerBlockData(Material.CORNFLOWER);
        registerBlockData(Material.WITHER_ROSE);
        registerBlockData(Material.LILY_OF_THE_VALLEY);
        registerBlockData(Material.BROWN_MUSHROOM);
        registerBlockData(Material.RED_MUSHROOM);
        registerBlockData(Material.GOLD_BLOCK);
        registerBlockData(Material.IRON_BLOCK);
        registerBlockData(Material.BRICKS);
        registerBlockData(Material.TNT, BlockDataTag.TNT_UNSTABLE);
        registerBlockData(Material.BOOKSHELF);
        registerBlockData(Material.MOSSY_COBBLESTONE);
        registerBlockData(Material.OBSIDIAN);
        registerBlockData(Material.TORCH);
        registerBlockData(Material.WALL_TORCH, BlockDataTag.WALL_TORCH);
        registerBlockData(Material.FIRE, BlockDataTag.FIRE_WEST, BlockDataTag.UP, BlockDataTag.FIRE_SOUTH, BlockDataTag.FIRE_NORTH, BlockDataTag.FIRE_EAST, BlockDataTag.FIRE_AGE);
        registerBlockData(Material.SOUL_FIRE);
        registerBlockData(Material.SPAWNER);
        registerBlockData(Material.OAK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.CHEST, BlockDataTag.WATERLOGGED, BlockDataTag.CHEST_TYPE, BlockDataTag.FACING);
        registerBlockData(Material.REDSTONE_WIRE, BlockDataTag.REDSTONE_WEST, BlockDataTag.REDSTONE_SOUTH, BlockDataTag.REDSTONE_POWER, BlockDataTag.REDSTONE_NORTH, BlockDataTag.REDSTONE_EAST);
        registerBlockData(Material.DIAMOND_ORE);
        registerBlockData(Material.DIAMOND_BLOCK);
        registerBlockData(Material.CRAFTING_TABLE);
        registerBlockData(Material.WHEAT, BlockDataTag.CROP_8);
        registerBlockData(Material.FARMLAND, BlockDataTag.FARMLAND_8);
        registerBlockData(Material.FURNACE, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.OAK_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.SPRUCE_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.BIRCH_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.JUNGLE_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.ACACIA_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.DARK_OAK_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.OAK_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.LADDER, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.RAIL, BlockDataTag.RAIL_FACING);
        registerBlockData(Material.COBBLESTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.OAK_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.SPRUCE_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.BIRCH_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.JUNGLE_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.ACACIA_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.DARK_OAK_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.LEVER, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.LEVER_FACING);
        registerBlockData(Material.IRON_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.OAK_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.SPRUCE_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.BIRCH_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.JUNGLE_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.ACACIA_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.DARK_OAK_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.REDSTONE_ORE, BlockDataTag.POWERED_BOOLEAN);
        registerBlockData(Material.REDSTONE_TORCH, BlockDataTag.LIT);
        registerBlockData(Material.REDSTONE_WALL_TORCH, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.STONE_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.SNOW, BlockDataTag.SNOW_LEVEL);
        registerBlockData(Material.ICE);
        registerBlockData(Material.SNOW_BLOCK);
        registerBlockData(Material.CACTUS, BlockDataTag.AGE);
        registerBlockData(Material.CLAY);
        registerBlockData(Material.SUGAR_CANE, BlockDataTag.AGE);
        registerBlockData(Material.JUKEBOX, BlockDataTag.JUKEBOX);
        registerBlockData(Material.OAK_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.PUMPKIN);
        registerBlockData(Material.NETHERRACK);
        registerBlockData(Material.SOUL_SAND);
        registerBlockData(Material.SOUL_SOIL);
        registerBlockData(Material.BASALT, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.POLISHED_BASALT, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.SOUL_TORCH);
        registerBlockData(Material.SOUL_WALL_TORCH, BlockDataTag.FACING);
        registerBlockData(Material.GLOWSTONE);
        registerBlockData(Material.NETHER_PORTAL, BlockDataTag.NETHER_PORTAL_DIRECTION);
        registerBlockData(Material.CAKE, BlockDataTag.BITES);
        registerBlockData(Material.REPEATER, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.LOCKED, BlockDataTag.FACING, BlockDataTag.REPEATER_TICK);
        registerBlockData(Material.WHITE_STAINED_GLASS);
        registerBlockData(Material.ORANGE_STAINED_GLASS);
        registerBlockData(Material.PURPLE_STAINED_GLASS);
        registerBlockData(Material.LIGHT_BLUE_STAINED_GLASS);
        registerBlockData(Material.YELLOW_STAINED_GLASS);
        registerBlockData(Material.LIME_STAINED_GLASS);
        registerBlockData(Material.PINK_STAINED_GLASS);
        registerBlockData(Material.GRAY_STAINED_GLASS);
        registerBlockData(Material.LIGHT_GRAY_STAINED_GLASS);
        registerBlockData(Material.CYAN_STAINED_GLASS);
        registerBlockData(Material.PURPLE_STAINED_GLASS);
        registerBlockData(Material.BLUE_STAINED_GLASS);
        registerBlockData(Material.BROWN_STAINED_GLASS);
        registerBlockData(Material.GREEN_STAINED_GLASS);
        registerBlockData(Material.RED_STAINED_GLASS);
        registerBlockData(Material.BLACK_STAINED_GLASS);
        registerBlockData(Material.OAK_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.SPRUCE_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.BIRCH_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.JUNGLE_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.ACACIA_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.DARK_OAK_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.STONE_BRICKS);
        registerBlockData(Material.MOSSY_STONE_BRICKS);
        registerBlockData(Material.CRACKED_STONE_BRICKS);
        registerBlockData(Material.CHISELED_STONE_BRICKS);
        registerBlockData(Material.INFESTED_STONE);
        registerBlockData(Material.INFESTED_COBBLESTONE);
        registerBlockData(Material.INFESTED_STONE_BRICKS);
        registerBlockData(Material.INFESTED_MOSSY_STONE_BRICKS);
        registerBlockData(Material.INFESTED_CRACKED_STONE_BRICKS);
        registerBlockData(Material.INFESTED_CHISELED_STONE_BRICKS);
        registerBlockData(Material.BROWN_MUSHROOM_BLOCK, BlockDataTag.WEST, BlockDataTag.UP, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST, BlockDataTag.DOWN);
        registerBlockData(Material.RED_MUSHROOM_BLOCK, BlockDataTag.WEST, BlockDataTag.UP, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST, BlockDataTag.DOWN);
        registerBlockData(Material.MUSHROOM_STEM, BlockDataTag.WEST, BlockDataTag.UP, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST, BlockDataTag.DOWN);
        registerBlockData(Material.IRON_BARS, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        //More like Glass PAIN
        registerBlockData(Material.MELON);
        registerBlockData(Material.ATTACHED_MELON_STEM, BlockDataTag.FACING);
        registerBlockData(Material.PUMPKIN_STEM, BlockDataTag.CROP_8);
        registerBlockData(Material.VINE, BlockDataTag.WEST, BlockDataTag.UP, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.OAK_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.STONE_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.NETHER_BRICK_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.NETHER_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.NETHER_WART, BlockDataTag.NETHER_WART_CROP);
        registerBlockData(Material.ENCHANTING_TABLE);
        registerBlockData(Material.BREWING_STAND, BlockDataTag.HAS_BOTTLE_0, BlockDataTag.HAS_BOTTLE_1, BlockDataTag.HAS_BOTTLE_2);
        registerBlockData(Material.CAULDRON, BlockDataTag.CAULDRON_LEVEL);
        registerBlockData(Material.END_PORTAL);
        registerBlockData(Material.END_PORTAL_FRAME, BlockDataTag.FACING, BlockDataTag.EYE);
        registerBlockData(Material.END_STONE);
        registerBlockData(Material.DRAGON_EGG);
        registerBlockData(Material.REDSTONE_LAMP, BlockDataTag.LIT);
        registerBlockData(Material.COCOA, BlockDataTag.FACING);
        registerBlockData(Material.COCOA, BlockDataTag.FACING);
        registerBlockData(Material.COCOA, BlockDataTag.FACING);
        registerBlockData(Material.COCOA, BlockDataTag.FACING);
        registerBlockData(Material.SANDSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.EMERALD_ORE);
        registerBlockData(Material.ENDER_CHEST, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.TRIPWIRE_HOOK, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.ATTACHED);
        registerBlockData(Material.TRIPWIRE, BlockDataTag.WEST, BlockDataTag.SOUTH, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.NORTH, BlockDataTag.EAST, BlockDataTag.DISARMED, BlockDataTag.ATTACHED);
        registerBlockData(Material.EMERALD_BLOCK);
        registerBlockData(Material.SPRUCE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.BIRCH_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.JUNGLE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.COMMAND_BLOCK, BlockDataTag.FACING, BlockDataTag.CONDITIONAL);
        registerBlockData(Material.BEACON);
        registerBlockData(Material.COBBLESTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.MOSSY_COBBLESTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.FLOWER_POT);
        registerBlockData(Material.POTTED_OAK_SAPLING);
        registerBlockData(Material.POTTED_SPRUCE_SAPLING);
        registerBlockData(Material.POTTED_BIRCH_SAPLING);
        registerBlockData(Material.POTTED_JUNGLE_SAPLING);
        registerBlockData(Material.POTTED_ACACIA_SAPLING);
        registerBlockData(Material.POTTED_DARK_OAK_SAPLING);
        registerBlockData(Material.POTTED_DANDELION);
        registerBlockData(Material.POTTED_POPPY);
        registerBlockData(Material.POTTED_BLUE_ORCHID);
        registerBlockData(Material.POTTED_ALLIUM);
        registerBlockData(Material.POTTED_AZURE_BLUET);
        registerBlockData(Material.POTTED_RED_TULIP);
        registerBlockData(Material.POTTED_ORANGE_TULIP);
        registerBlockData(Material.POTTED_WHITE_TULIP);
        registerBlockData(Material.POTTED_PINK_TULIP);
        registerBlockData(Material.POTTED_OXEYE_DAISY);
        registerBlockData(Material.POTTED_CORNFLOWER);
        registerBlockData(Material.POTTED_LILY_OF_THE_VALLEY);
        registerBlockData(Material.POTTED_WITHER_ROSE);
        registerBlockData(Material.POTTED_RED_MUSHROOM);
        registerBlockData(Material.POTTED_BROWN_MUSHROOM);
        registerBlockData(Material.POTTED_DEAD_BUSH);
        registerBlockData(Material.POTTED_CACTUS);
        registerBlockData(Material.CARROTS, BlockDataTag.CROP_8);
        registerBlockData(Material.POTATOES, BlockDataTag.CROP_8);
        registerBlockData(Material.OAK_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.SPRUCE_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.BIRCH_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.JUNGLE_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.ACACIA_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.DARK_OAK_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.SKELETON_SKULL, BlockDataTag.ROTATION);
        registerBlockData(Material.SKELETON_WALL_SKULL, BlockDataTag.FACING);
        registerBlockData(Material.WITHER_SKELETON_SKULL, BlockDataTag.ROTATION);
        registerBlockData(Material.WITHER_SKELETON_WALL_SKULL, BlockDataTag.FACING);
        registerBlockData(Material.ZOMBIE_HEAD, BlockDataTag.ROTATION);
        registerBlockData(Material.ZOMBIE_WALL_HEAD, BlockDataTag.FACING);
        registerBlockData(Material.PLAYER_HEAD, BlockDataTag.ROTATION);
        registerBlockData(Material.PLAYER_WALL_HEAD, BlockDataTag.FACING);
        registerBlockData(Material.CREEPER_HEAD, BlockDataTag.ROTATION);
        registerBlockData(Material.CREEPER_WALL_HEAD, BlockDataTag.FACING);
        registerBlockData(Material.DRAGON_HEAD, BlockDataTag.ROTATION);
        registerBlockData(Material.DRAGON_WALL_HEAD, BlockDataTag.FACING);
        registerBlockData(Material.ANVIL, BlockDataTag.FACING);
        registerBlockData(Material.CHIPPED_ANVIL, BlockDataTag.FACING);
        registerBlockData(Material.DAMAGED_ANVIL, BlockDataTag.FACING);
        registerBlockData(Material.TRAPPED_CHEST, BlockDataTag.WATERLOGGED, BlockDataTag.CHEST_TYPE, BlockDataTag.FACING);
        registerBlockData(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, BlockDataTag.POWERED);
        registerBlockData(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, BlockDataTag.POWERED);
        registerBlockData(Material.COMPARATOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.COMPARATOR_MODE, BlockDataTag.FACING);
        registerBlockData(Material.DAYLIGHT_DETECTOR, BlockDataTag.POWERED, BlockDataTag.INVERTED);
        registerBlockData(Material.REDSTONE_BLOCK);
        registerBlockData(Material.NETHER_QUARTZ_ORE);
        registerBlockData(Material.HOPPER, BlockDataTag.HOPPER_FACING, BlockDataTag.HOPPER_ENABLED);
        registerBlockData(Material.QUARTZ_BLOCK);
        registerBlockData(Material.CHISELED_QUARTZ_BLOCK);
        registerBlockData(Material.QUARTZ_PILLAR, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.QUARTZ_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.ACTIVATOR_RAIL, BlockDataTag.POWERED_RAIL_FACING, BlockDataTag.POWERED_BOOLEAN);
        registerBlockData(Material.DROPPER, BlockDataTag.DIRECTION, BlockDataTag.TRIGGERED);
        registerBlockData(Material.WHITE_TERRACOTTA);
        registerBlockData(Material.ORANGE_TERRACOTTA);
        registerBlockData(Material.MAGENTA_TERRACOTTA);
        registerBlockData(Material.LIGHT_BLUE_TERRACOTTA);
        registerBlockData(Material.YELLOW_TERRACOTTA);
        registerBlockData(Material.LIME_TERRACOTTA);
        registerBlockData(Material.PINK_TERRACOTTA);
        registerBlockData(Material.GRAY_TERRACOTTA);
        registerBlockData(Material.LIGHT_GRAY_TERRACOTTA);
        registerBlockData(Material.CYAN_TERRACOTTA);
        registerBlockData(Material.PURPLE_TERRACOTTA);
        registerBlockData(Material.BLUE_TERRACOTTA);
        registerBlockData(Material.BROWN_TERRACOTTA);
        registerBlockData(Material.GREEN_TERRACOTTA);
        registerBlockData(Material.RED_TERRACOTTA);
        registerBlockData(Material.BLACK_TERRACOTTA);
        registerBlockData(Material.WHITE_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.ORANGE_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.MAGENTA_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.LIGHT_BLUE_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.YELLOW_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.LIME_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.PINK_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.GRAY_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.LIGHT_GRAY_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.CYAN_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.PURPLE_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.BLUE_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.BROWN_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.GREEN_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.RED_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);
        registerBlockData(Material.BLACK_STAINED_GLASS_PANE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST);

        registerBlockData(Material.ACACIA_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.DARK_OAK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.SLIME_BLOCK);
        registerBlockData(Material.IRON_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.PRISMARINE);
        registerBlockData(Material.PRISMARINE_BRICKS);
        registerBlockData(Material.DARK_PRISMARINE);
        registerBlockData(Material.PRISMARINE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.PRISMARINE_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.DARK_PRISMARINE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.PRISMARINE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.PRISMARINE_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.DARK_PRISMARINE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SEA_LANTERN);
        registerBlockData(Material.HAY_BLOCK, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.WHITE_CARPET);
        registerBlockData(Material.ORANGE_CARPET);
        registerBlockData(Material.MAGENTA_CARPET);
        registerBlockData(Material.LIGHT_BLUE_CARPET);
        registerBlockData(Material.YELLOW_CARPET);
        registerBlockData(Material.LIME_CARPET);
        registerBlockData(Material.PINK_CARPET);
        registerBlockData(Material.GRAY_CARPET);
        registerBlockData(Material.LIGHT_GRAY_CARPET);
        registerBlockData(Material.CYAN_CARPET);
        registerBlockData(Material.PURPLE_CARPET);
        registerBlockData(Material.BLUE_CARPET);
        registerBlockData(Material.BROWN_CARPET);
        registerBlockData(Material.GREEN_CARPET);
        registerBlockData(Material.RED_CARPET);
        registerBlockData(Material.BLACK_CARPET);
        registerBlockData(Material.TERRACOTTA);
        registerBlockData(Material.COAL_BLOCK);
        registerBlockData(Material.PACKED_ICE);
        registerBlockData(Material.SUNFLOWER, BlockDataTag.HALF);
        registerBlockData(Material.LILAC, BlockDataTag.HALF);
        registerBlockData(Material.ROSE_BUSH, BlockDataTag.HALF);
        registerBlockData(Material.PEONY, BlockDataTag.HALF);
        registerBlockData(Material.TALL_GRASS, BlockDataTag.HALF);
        registerBlockData(Material.LARGE_FERN, BlockDataTag.HALF);
        registerBlockData(Material.WHITE_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.ORANGE_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.MAGENTA_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.LIGHT_BLUE_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.YELLOW_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.LIME_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.PINK_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.GRAY_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.LIGHT_GRAY_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.CYAN_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.PURPLE_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.BLUE_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.BROWN_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.GREEN_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.RED_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.BLACK_BANNER, BlockDataTag.ROTATION);
        registerBlockData(Material.RED_SANDSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.OAK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SPRUCE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.BIRCH_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.JUNGLE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.ACACIA_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.DARK_OAK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.STONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SMOOTH_STONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.CUT_SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.PETRIFIED_OAK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.COBBLESTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.STONE_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.NETHER_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.QUARTZ_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.RED_SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.CUT_RED_SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.PURPUR_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SMOOTH_STONE);
        registerBlockData(Material.SMOOTH_SANDSTONE);
        registerBlockData(Material.SMOOTH_QUARTZ);
        registerBlockData(Material.SMOOTH_RED_SANDSTONE);
        registerBlockData(Material.SPRUCE_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.BIRCH_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.JUNGLE_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.ACACIA_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.DARK_OAK_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.SPRUCE_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.BIRCH_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.JUNGLE_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.ACACIA_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.DARK_OAK_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.SPRUCE_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.BIRCH_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.JUNGLE_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.ACACIA_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.DARK_OAK_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.END_ROD, BlockDataTag.DIRECTION);
        registerBlockData(Material.CHORUS_PLANT, BlockDataTag.WEST, BlockDataTag.UP, BlockDataTag.SOUTH, BlockDataTag.NORTH, BlockDataTag.EAST, BlockDataTag.DOWN);
        registerBlockData(Material.CHORUS_FLOWER, BlockDataTag.CHORUSFLOWER);
        registerBlockData(Material.PURPUR_BLOCK);
        registerBlockData(Material.PURPUR_PILLAR, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.PURPUR_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.END_STONE_BRICKS);
        registerBlockData(Material.BEETROOTS, BlockDataTag.CROP_8);
        registerBlockData(Material.GRASS_PATH);
        registerBlockData(Material.END_GATEWAY);
        registerBlockData(Material.REPEATING_COMMAND_BLOCK, BlockDataTag.FACING, BlockDataTag.CONDITIONAL);
        registerBlockData(Material.CHAIN_COMMAND_BLOCK, BlockDataTag.FACING, BlockDataTag.CONDITIONAL);
        registerBlockData(Material.FROSTED_ICE, BlockDataTag.FROSTED_ICE_AGE);
        registerBlockData(Material.MAGMA_BLOCK);
        registerBlockData(Material.NETHER_WART_BLOCK);
        registerBlockData(Material.RED_NETHER_BRICKS);
        registerBlockData(Material.BONE_BLOCK, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRUCTURE_VOID);
        registerBlockData(Material.OBSERVER, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.DIRECTION);
        registerBlockData(Material.SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.WHITE_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.ORANGE_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.MAGENTA_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.LIGHT_BLUE_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.YELLOW_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.LIME_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.PINK_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.GRAY_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.LIGHT_GRAY_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.CYAN_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.PURPLE_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.GREEN_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.RED_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.BLACK_SHULKER_BOX, BlockDataTag.DIRECTION);
        registerBlockData(Material.WHITE_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.ORANGE_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.MAGENTA_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.LIGHT_BLUE_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.YELLOW_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.LIME_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.PINK_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.GRAY_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.LIGHT_GRAY_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.CYAN_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.PURPLE_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.GREEN_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.RED_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.BLACK_GLAZED_TERRACOTTA, BlockDataTag.FACING);
        registerBlockData(Material.WHITE_CONCRETE);
        registerBlockData(Material.ORANGE_CONCRETE);
        registerBlockData(Material.MAGENTA_CONCRETE);
        registerBlockData(Material.LIGHT_BLUE_CONCRETE);
        registerBlockData(Material.YELLOW_CONCRETE);
        registerBlockData(Material.LIME_CONCRETE);
        registerBlockData(Material.PINK_CONCRETE);
        registerBlockData(Material.GRAY_CONCRETE);
        registerBlockData(Material.LIGHT_GRAY_CONCRETE);
        registerBlockData(Material.CYAN_CONCRETE);
        registerBlockData(Material.PURPLE_CONCRETE);
        registerBlockData(Material.BLUE_CONCRETE);
        registerBlockData(Material.BROWN_CONCRETE);
        registerBlockData(Material.GREEN_CONCRETE);
        registerBlockData(Material.RED_CONCRETE);
        registerBlockData(Material.BLACK_CONCRETE);
        registerBlockData(Material.WHITE_CONCRETE_POWDER);
        registerBlockData(Material.ORANGE_CONCRETE_POWDER);
        registerBlockData(Material.MAGENTA_CONCRETE_POWDER);
        registerBlockData(Material.LIGHT_BLUE_CONCRETE_POWDER);
        registerBlockData(Material.YELLOW_CONCRETE_POWDER);
        registerBlockData(Material.LIME_CONCRETE_POWDER);
        registerBlockData(Material.PINK_CONCRETE_POWDER);
        registerBlockData(Material.GRAY_CONCRETE_POWDER);
        registerBlockData(Material.LIGHT_GRAY_CONCRETE_POWDER);
        registerBlockData(Material.CYAN_CONCRETE_POWDER);
        registerBlockData(Material.PURPLE_CONCRETE_POWDER);
        registerBlockData(Material.BLUE_CONCRETE_POWDER);
        registerBlockData(Material.BROWN_CONCRETE_POWDER);
        registerBlockData(Material.GREEN_CONCRETE_POWDER);
        registerBlockData(Material.RED_CONCRETE_POWDER);
        registerBlockData(Material.BLACK_CONCRETE_POWDER);
        registerBlockData(Material.KELP_PLANT, BlockDataTag.AGE);
        registerBlockData(Material.DRIED_KELP_BLOCK);
        registerBlockData(Material.TURTLE_EGG, BlockDataTag.HATCH, BlockDataTag.EGGS);
        registerBlockData(Material.DEAD_TUBE_CORAL_BLOCK);
        registerBlockData(Material.DEAD_BRAIN_CORAL_BLOCK);
        registerBlockData(Material.DEAD_BUBBLE_CORAL_BLOCK);
        registerBlockData(Material.DEAD_FIRE_CORAL_BLOCK);
        registerBlockData(Material.DEAD_HORN_CORAL_BLOCK);
        registerBlockData(Material.TUBE_CORAL_BLOCK);
        registerBlockData(Material.BRAIN_CORAL_BLOCK);
        registerBlockData(Material.BUBBLE_CORAL_BLOCK);
        registerBlockData(Material.FIRE_CORAL_BLOCK);
        registerBlockData(Material.HORN_CORAL_BLOCK);
        registerBlockData(Material.DEAD_TUBE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_BRAIN_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_BUBBLE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_FIRE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_HORN_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.TUBE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.BRAIN_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.BUBBLE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.FIRE_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.HORN_CORAL, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_TUBE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_BRAIN_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_BUBBLE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_FIRE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_HORN_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.TUBE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.BRAIN_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.BUBBLE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.FIRE_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.HORN_CORAL_FAN, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.DEAD_TUBE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.DEAD_BRAIN_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.DEAD_BUBBLE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.DEAD_FIRE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.DEAD_HORN_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.TUBE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.BRAIN_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.BUBBLE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.FIRE_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.HORN_CORAL_FAN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.SEA_PICKLE, BlockDataTag.WATERLOGGED, BlockDataTag.SEAPICKLES);
        registerBlockData(Material.BLUE_ICE);
        registerBlockData(Material.CONDUIT, BlockDataTag.WATERLOGGED);
        registerBlockData(Material.BAMBOO_SAPLING);
        registerBlockData(Material.BAMBOO, BlockDataTag.BAMBOO_STAGE, BlockDataTag.BAMBOO_LEAVES, BlockDataTag.BAMBOO_AGE);
        registerBlockData(Material.POLISHED_GRANITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.SMOOTH_RED_SANDSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.MOSSY_STONE_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.POLISHED_DIORITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.MOSSY_COBBLESTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.END_STONE_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.STONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.SMOOTH_SANDSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.SMOOTH_QUARTZ_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.GRANITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.ANDESITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.RED_NETHER_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.POLISHED_ANDESITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.DIORITE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.POLISHED_GRANITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SMOOTH_RED_SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.MOSSY_STONE_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.POLISHED_DIORITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.MOSSY_COBBLESTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.END_STONE_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SMOOTH_SANDSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.SMOOTH_QUARTZ_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.GRANITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.ANDESITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.RED_NETHER_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.POLISHED_ANDESITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.DIORITE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.PRISMARINE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.RED_SANDSTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.MOSSY_STONE_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.GRANITE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.STONE_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.NETHER_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.ANDESITE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.RED_NETHER_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.SANDSTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.END_STONE_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.DIORITE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.SCAFFOLDING, BlockDataTag.WATERLOGGED, BlockDataTag.SCAFFOLDING_DISTANCE, BlockDataTag.SCAFFOLDING_BOTTOM);
        registerBlockData(Material.LOOM, BlockDataTag.FACING);
        registerBlockData(Material.BARREL, BlockDataTag.OPEN, BlockDataTag.FACING);
        registerBlockData(Material.SMOKER, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.BLAST_FURNACE, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.CARTOGRAPHY_TABLE);
        registerBlockData(Material.FLETCHING_TABLE);
        registerBlockData(Material.GRINDSTONE, BlockDataTag.FACING, BlockDataTag.GRINDSTONE_FACE);
        registerBlockData(Material.LECTERN, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.HAS_BOOK, BlockDataTag.FACING);
        registerBlockData(Material.SMITHING_TABLE);
        registerBlockData(Material.STONECUTTER, BlockDataTag.FACING);
        registerBlockData(Material.BELL, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BELL_ATTACHMENT);
        registerBlockData(Material.LANTERN, BlockDataTag.WATERLOGGED, BlockDataTag.LANTERN_HANGING);
        registerBlockData(Material.SOUL_LANTERN, BlockDataTag.WATERLOGGED, BlockDataTag.LANTERN_HANGING);
        registerBlockData(Material.CAMPFIRE, BlockDataTag.WATERLOGGED, BlockDataTag.CAMPFIRE_SIGNAL_FIRE, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.SOUL_CAMPFIRE, BlockDataTag.WATERLOGGED, BlockDataTag.CAMPFIRE_SIGNAL_FIRE, BlockDataTag.LIT, BlockDataTag.FACING);
        registerBlockData(Material.SWEET_BERRY_BUSH, BlockDataTag.BERRYBUSH);
        registerBlockData(Material.WARPED_STEM, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_WARPED_STEM, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.WARPED_HYPHAE, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_WARPED_HYPHAE, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.WARPED_NYLIUM);
        registerBlockData(Material.WARPED_FUNGUS);
        registerBlockData(Material.WARPED_WART_BLOCK);
        registerBlockData(Material.WARPED_ROOTS);
        registerBlockData(Material.NETHER_SPROUTS);
        registerBlockData(Material.CRIMSON_STEM, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_CRIMSON_STEM, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.CRIMSON_HYPHAE, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.STRIPPED_CRIMSON_HYPHAE, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.CRIMSON_STEM, BlockDataTag.DIRECTIONAL);
        registerBlockData(Material.CRIMSON_NYLIUM);
        registerBlockData(Material.CRIMSON_FUNGUS);
        registerBlockData(Material.SHROOMLIGHT);
        registerBlockData(Material.WEEPING_VINES, BlockDataTag.WEEPINGVINES);
        registerBlockData(Material.WEEPING_VINES_PLANT);
        registerBlockData(Material.TWISTING_VINES, BlockDataTag.TWISTINGVINES);
        registerBlockData(Material.TWISTING_VINES_PLANT);
        registerBlockData(Material.CRIMSON_PLANKS);
        registerBlockData(Material.WARPED_PLANKS);
        registerBlockData(Material.CRIMSON_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.WARPED_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.CRIMSON_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.WARPED_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.CRIMSON_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.WARPED_FENCE, BlockDataTag.WEST, BlockDataTag.WATERLOGGED, BlockDataTag.NORTH, BlockDataTag.SOUTH, BlockDataTag.EAST);
        registerBlockData(Material.CRIMSON_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.WARPED_TRAPDOOR, BlockDataTag.WATERLOGGED, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.CRIMSON_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.WARPED_FENCE_GATE, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.IN_WALL, BlockDataTag.FACING);
        registerBlockData(Material.CRIMSON_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.WARPED_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.CRIMSON_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.WARPED_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.CRIMSON_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.WARPED_DOOR, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.OPEN, BlockDataTag.HINGE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.CRIMSON_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.WARPED_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.ROTATION);
        registerBlockData(Material.CRIMSON_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.WARPED_WALL_SIGN, BlockDataTag.WATERLOGGED, BlockDataTag.FACING);
        registerBlockData(Material.JIGSAW, BlockDataTag.JIGSAW);
        registerBlockData(Material.COMPOSTER, BlockDataTag.COMPOSTER);
        registerBlockData(Material.TARGET, BlockDataTag.POWERED);
        registerBlockData(Material.BEE_NEST, BlockDataTag.HIVE_HONEY_LEVEL, BlockDataTag.FACING);
        registerBlockData(Material.BEEHIVE, BlockDataTag.HIVE_HONEY_LEVEL, BlockDataTag.FACING);
        registerBlockData(Material.HONEY_BLOCK);
        registerBlockData(Material.HONEYCOMB_BLOCK);
        registerBlockData(Material.NETHERITE_BLOCK);
        registerBlockData(Material.ANCIENT_DEBRIS);
        registerBlockData(Material.CRYING_OBSIDIAN);
        registerBlockData(Material.RESPAWN_ANCHOR, BlockDataTag.RESPAWN_ANCHOR);
        registerBlockData(Material.POTTED_CRIMSON_FUNGUS);
        registerBlockData(Material.POTTED_WARPED_FUNGUS);
        registerBlockData(Material.POTTED_CRIMSON_ROOTS);
        registerBlockData(Material.POTTED_WARPED_ROOTS);
        registerBlockData(Material.LODESTONE);
        registerBlockData(Material.BLACKSTONE);
        registerBlockData(Material.BLACKSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.BLACKSTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.BLACKSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.POLISHED_BLACKSTONE);
        registerBlockData(Material.POLISHED_BLACKSTONE_BRICKS);
        registerBlockData(Material.CRACKED_POLISHED_BLACKSTONE_BRICKS);
        registerBlockData(Material.CHISELED_POLISHED_BLACKSTONE);
        registerBlockData(Material.POLISHED_BLACKSTONE_BRICK_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.POLISHED_BLACKSTONE_BRICK_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.POLISHED_BLACKSTONE_BRICK_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
        registerBlockData(Material.GILDED_BLACKSTONE);
        registerBlockData(Material.POLISHED_BLACKSTONE_STAIRS, BlockDataTag.WATERLOGGED, BlockDataTag.STAIR_SHAPE, BlockDataTag.HALF, BlockDataTag.FACING);
        registerBlockData(Material.POLISHED_BLACKSTONE_SLAB, BlockDataTag.WATERLOGGED, BlockDataTag.SLAB_TYPE);
        registerBlockData(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, BlockDataTag.PRESSURE_PLATE_PRESSED);
        registerBlockData(Material.POLISHED_BLACKSTONE_BUTTON, BlockDataTag.POWERED_BOOLEAN, BlockDataTag.FACING, BlockDataTag.BUTTON_FACE);
        registerBlockData(Material.POLISHED_BLACKSTONE_WALL, BlockDataTag.WALL_WEST_TYPE, BlockDataTag.WATERLOGGED, BlockDataTag.UP, BlockDataTag.WALL_SOUTH_TYPE, BlockDataTag.WALL_NORTH_TYPE, BlockDataTag.WALL_EAST_TYPE);
    }

}
