package com.projectomega.main.game.block;

public enum BlockDataTag {

    DIRECTIONAL(3),
    POWERED(16),
    NOTEBLOCK_TYPE(10),
    WALL_NORTH_TYPE(3),
    WALL_SOUTH_TYPE(3),
    WALL_EAST_TYPE(3),
    WALL_WEST_TYPE(3),
    WATERLOGGED(2),
    GRASS(2), SAPLING(2), WATER_FALLING(2), WATER_LEVEL(8), LEAVES_LEVEL(7),
    PERSISTANT(2), TRIGGERED(2), DIRECTION(6), NOTEBLOCK_TONE(24), FACING(4), BED_OCCUPIED(2), BED_HEADFOOT(2), POWERED_RAIL_FACING(6),
    PISTON_EXTENDED(2), TWO_TALL(2), PISTON_HEAD_STICKY(2), TNT_UNSTABLE(2),
    WALL_TORCH(4), FIRE_WEST(2), UP(2), FIRE_SOUTH(2), FIRE_NORTH(2), FIRE_EAST(2), FIRE_AGE(16), STAIR_SHAPE(5), HALF(2),
    CHEST_TYPE(3), REDSTONE_POWER(16), REDSTONE_SOUTH(3), REDSTONE_WEST(3), REDSTONE_EAST(3), REDSTONE_NORTH(3), CROP_8(8),
    FARMLAND_8(8), LIT(2), ROTATION(16), POWERED_BOOLEAN(2), OPEN(2), HINGE(2), RAIL_FACING(10),
    LEVER_FACING(3), PRESSURE_PLATE_PRESSED(2), BUTTON_FACE(3), SNOW_LEVEL(8), AGE(16),
    JUKEBOX(2), WEST(2), NORTH(2), EAST(2), SOUTH(2), NETHER_PORTAL_DIRECTION(2), BITES(7), LOCKED(2), REPEATER_TICK(4), DOWN(2), IN_WALL(2),
    NETHER_WART_CROP(4), HAS_BOTTLE_0(2), HAS_BOTTLE_2(2), HAS_BOTTLE_1(2), CAULDRON_LEVEL(4), EYE(2), ATTACHED(2),
    DISARMED(2), CONDITIONAL(2), COMPARATOR_MODE(2), INVERTED(2), HOPPER_FACING(5), HOPPER_ENABLED(2), SLAB_TYPE(3), CHORUSFLOWER(6), FROSTED_ICE_AGE(4), HATCH(3), EGGS(4), SEAPICKLES(4),
    BAMBOO_STAGE(2), BAMBOO_LEAVES(3), BAMBOO_AGE(2), SCAFFOLDING_DISTANCE(8), SCAFFOLDING_BOTTOM(2), GRINDSTONE_FACE(3), HAS_BOOK(2),
    BELL_ATTACHMENT(3), LANTERN_HANGING(2), CAMPFIRE_SIGNAL_FIRE(2), BERRYBUSH(4), WEEPINGVINES(26), TWISTINGVINES(26), JIGSAW(16), COMPOSTER(8),
    HIVE_HONEY_LEVEL(6), RESPAWN_ANCHOR(5);

    public int getStateCount() {
        return statecount;
    }

    private int statecount;

    BlockDataTag(int statecount) {
        this.statecount = statecount;
    }

    enum DirectionalTag {
        X_AXIS,
        Y_AXIS,
        Z_AXIS;
    }
}
