package com.projectomega.main.game.entity;

public enum EntityType {

    AREA_EFFECT_CLOUD(0,false),
    ARMOR_STAND(1,true),
    ARROW(2,false),
    BAT(3,true),
    BEE(4,true),
    BLAZE(5,true),
    BOAT(6,false),
    CAT(7,true),
    CAVESPIDER(8,true),
    CHICKEN(9,true),
    COD(10,true),
    COW(11,true),
    CREEPER(12,true),
    DONKEY(13,true),
    DOLPHIN(14,true),
    DRAGON_FIREBALL(15,true),
    DROWNED(16,true),
    ELDER_GUADIAN(17,true),
    ENDER_CRYSTAL(18,false),
    ENDER_DRAGON(19,true),
    ENDERMAN(20,true),
    ENDERMITE(21,true),
    EVOCATION_FANG(22,false),
    EVOCATIONILLAGER(23,true),
    XP_ORB(24,false),
    EYE_IF_ENDER_SIGNAL(25,false),
    FALLING_SAND(26,false),
    FIREWORK_ROCKET(27,false),
    FOX(28,true),
    GHAST(29,true),
    GIANT(30,true),
    GUARDIAN(31,true),
    HORSE(32,true),
    HUSK(33,true),
    ILLUSION_ILLAGER(34,true),
    ITEM(35,false),
    ITEM_FRAME(36,false),
    FIREBALL(37,false),
    LEASH_KNOT(38,false),
    LLAMA(39,true),
    LLAMA_SPIT(40,false),
    LAVA_SLIME(41,true),
    MINECART_RIDABLE(42,false),
    MINECART_CHEST(43,false),
    MINECART_COMMANDBLOCK(44,false),
    MINECART_FURNACE(45,false),
    MINECART_HOPPER(46,false),
    MINECART_SPAWNER(47,false),
    MINECART_TNT(48,false),
    MULE(49,true),
    MUSHROOM_COW(50,true),
    OZELOT(51,true),
    PAINTING(52,false),
    PANDA(53,true),
    PARROT(54,true),
    PIG(55,true),
    PUFFERFISH(56,true),
    PIG_ZOMBIE(57,true),
    POLAR_BEAR(58,true),
    PRIMED_TNT(59,false),
    RABBIT(60,true),
    SALMON(61,true),
    SHEEP(62,true),
    SHULKER(63,true),
    SHULKER_BULLET(64, false),
    SILVERFISH(65,true),
    SKELETON(66,true),
    SKELETON_HORSE(67,true),
    SLIME(68,true),
    SMALL_FIREBALL(69,false ),
    SNOWMAN(70,true),
    SNOWBALL(71, false),
    SPECTRAL_ARROW(72, false),
    SPIDER(73,true),
    SQUID(74,true),
    STRAY(75,true),
    TRADER_LLAMA(76,true),
    TROPICAL_FISH(77,true),
    TURTLE(78,true),
    THROWN_EGG(79,false),
    THROWN_ENDERPEARL(80, false),
    THROWN_EXP_BOTTLE(81,false),
    THROWN_POTION(82,false),
    THROWN_TRIDENT(83,false),
    VEX(84,true),
    VILLAGER(85,true),
    VILLAGER_GOLEM(86,true),
    VINDICATER_ILLAGER(87,true),
    VINDICATER_PILLAGER(88,true),
    WANDERING_TRADER(89,true),
    WITCH(90,true),
    WITHER_BOSS(91,true),
    WITHER_SKELETON(92,true),
    WITHER_SKULL(93,false),
    WOLF(94,true),
    ZOMBIE(95,true),
    ZOMBIE_HORSE(96,true),
    ZOMBIE_VILLAGER(97,true),
    PHANTOM(98,true),
    RAVAGER(99,true),
    LIGHTNING_BOLT(100,false),
    PLAYER(101,false),
    FISHING_BOBBER(102,false),
    ;

    private int typeid;
    private boolean living;

    EntityType(int id, boolean living) {
        typeid = id;
        this.living = living;
    }

    public int getTypeID() {
        return typeid;
    }

    public boolean isLiving() {
        return living;
    }
}
